# Generated by Django 3.2 on 2021-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=80)),
                ('student_dob', models.DateField()),
                ('student_doj', models.DateField()),
            ],
        ),
    ]
